"""Build the complete ThermoLab site — both language copies and the JupyterLite app.

    _site/index.html  -> redirect to /en/
    _site/en/...      -> English site
    _site/he/...      -> Hebrew site (RTL)
    _site/lite/...    -> JupyterLite app serving notebooks/<lang>/labs/*.ipynb

This is the single entry point: every generated artifact a published site needs is produced
here, in dependency order, because several of them are gitignored and therefore absent from a
fresh clone (`content/<lang>/_generated/`, `content/<lang>/media/`). Building only the MyST
projects yields a site with empty quiz includes and broken image links.

    stylesheets -> quizzes -> animations -> myst (per language) -> assemble -> jupyterlite

Each language is an independent MyST project built with BASE_URL=<base>/<lang> so its internal
links resolve under that prefix. `<base>` is empty for a site served from the root of a domain
and `/thermolab` for a GitHub Pages project site; see `--base-path`. JupyterLite is built last,
into the assembled tree, because `_site/` is the only place where /en/, /he/ and /lite/ share an
origin — which is what makes the `/lite/lab/index.html?path=<lang>/labs/<module>.ipynb` links on
the module pages resolve. Those links cannot work under `npx myst start`: that server serves one
MyST project and knows nothing about /lite.

MyST rewrites a root-absolute link target into BASE_URL, so `/lite/lab/index.html` written in a
page is emitted as `<base>/<lang>/lite/lab/index.html` — an address the single shared bundle does
not occupy. `write_lab_redirects` puts a relative redirect there rather than duplicating the
bundle per language; `verify_lite` then refuses to ship a lab link that does not resolve.

The `thermolab` wheel is built into `dist/` and indexed into the bundle by JupyterLite's
PipliteAddon, because Pyodide has no access to this repository: without it every notebook dies
on `from thermolab import ...`.

Run:  uv run python scripts/build_site.py [--no-lite] [--no-clean]
                                          [--media|--no-media] [--serve [PORT]]
                                          [--base-path PREFIX]

Why there is no HTML post-processing here: the mystmd book theme is a hydrating React app
that rebuilds the document after load, discarding anything injected into the static HTML
(styles, scripts, added elements, and `lang`/`dir` attributes). Everything language-specific
therefore goes through configuration the theme itself honours — `site.options.style` for the
stylesheet (generated by scripts/build_css.py) and `site.options.logo_text` for the header
title. Known limitation of that trade-off: the theme's own chrome ("Search", "CONTENTS", …)
stays English on the Hebrew copy, and `<html lang>` is not language-tagged.

The two language copies do not link to each other; _site/index.html is the only chooser.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from urllib.parse import urlsplit

sys.path.insert(0, str(Path(__file__).resolve().parent))

import render_quizzes  # noqa: E402
from build_css import generate as generate_css  # noqa: E402

from _findings import ensure_stdout_can_print_unicode  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / "_site"
LANGS = ("en", "he")
RENDER_DIR = ROOT / "media" / "render"
LITE_DOIT_DB = ROOT / ".jupyterlite.doit.db"
# Where `uv build` puts the wheel and where jupyter_lite_config.json looks for it.
WHEEL_DIR = ROOT / "dist"
PACKAGE = "thermolab"
# What media/render/*.py may emit into content/<lang>/media/, for the staleness check only.
MEDIA_SUFFIXES = {".gif", ".mp4", ".webm", ".png"}
# A root-absolute link into the JupyterLite bundle, as written in a content page.
LAB_LINK = re.compile(r"/lite/[^\s)\]\"'<>]+")

ROOT_REDIRECT = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>ThermoLab</title>
<meta http-equiv="refresh" content="0; url=./en/">
<script>location.replace("./en/");</script>
</head>
<body>
<p><a href="./en/">English</a> &middot; <a href="./he/" lang="he">עברית</a></p>
</body>
</html>
"""


@dataclass
class Stage:
    """One build step's outcome, so the summary can report every stage at once."""

    name: str
    ok: bool = True
    detail: str = ""
    problems: list[str] = field(default_factory=list)


def heading(name: str) -> None:
    print(f"\n=== {name} ===")


def myst_executable() -> str:
    exe = ROOT / "node_modules" / ".bin" / ("myst.cmd" if os.name == "nt" else "myst")
    if not exe.exists():
        sys.exit("mystmd not found — run `npm install` first")
    return str(exe)


def uv_executable() -> str:
    """Locate uv, which builds the wheel that JupyterLite serves to Pyodide.

    uv is not importable from the virtualenv it created, and `uv run` does not put it on PATH,
    so it has to be found the same way build.sh/build.ps1 find it. Those wrappers export UV
    with the path they already resolved, which is checked first.
    """
    candidate = os.environ.get("UV") or shutil.which("uv")
    if candidate and Path(candidate).exists():
        return candidate

    home = Path.home()
    for fallback in (home / ".local/bin/uv", home / ".local/bin/uv.exe"):
        if fallback.exists():
            return str(fallback)

    sys.exit("uv not found — set UV, put it on PATH, or install it from https://docs.astral.sh/uv/")


def normalise_base_path(value: str) -> str:
    """Canonicalise a deployment prefix to "" (domain root) or "/prefix".

    `actions/configure-pages` reports "/" for a user site or custom domain and "/thermolab" for
    a project site; a human is as likely to type "thermolab/". All three have to mean the same
    thing, because the prefix is concatenated with "/<lang>" to form BASE_URL.
    """
    trimmed = value.strip().strip("/")
    return f"/{trimmed}" if trimmed else ""


def build_stylesheets() -> Stage:
    heading("stylesheets")
    written = generate_css()
    for path in written:
        print(f"wrote {path.relative_to(ROOT)}")
    return Stage("stylesheets", detail=f"{len(written)} file(s)")


def build_quizzes() -> Stage:
    """Render both quiz outputs before MyST runs.

    The site rendering (`content/<lang>/_generated/quiz-<module>.md`) is gitignored, so on a
    fresh clone the module pages would include a file that does not exist; the notebook
    rendering feeds the JupyterLite bundle.
    """
    heading("quizzes")
    written, findings = render_quizzes.generate()
    for path in written:
        print(f"wrote {path.relative_to(ROOT)}")
    errors = [str(f) for f in findings if f.severity == "error"]
    for finding in findings:
        print(finding)
    if not written and not findings:
        print("no quiz banks found")
    return Stage("quizzes", ok=not errors, detail=f"{len(written)} file(s)", problems=errors)


def media_is_stale() -> tuple[bool, str]:
    """Decide whether the animations need re-rendering.

    Rendering is minutes of simulation, so it must not run on every build — but the outputs
    are gitignored, and they are produced *from* `thermolab`, so a stale cache would show the
    reader an animation of physics the code no longer implements. Compare the newest render
    script or physics source against the oldest existing animation.

    Any known animation extension counts, not just the .mp4 the render scripts currently emit,
    so the build does not silently stop tracking staleness if that changes. Note .webm is
    listed for staleness only — mystmd cannot render it (the theme tests a literal
    `.endsWith(".mp4")`), so emitting webm would produce an empty player.
    """
    rendered = [
        path
        for lang in LANGS
        for path in (ROOT / "content" / lang / "media").glob("*")
        if path.suffix.lower() in MEDIA_SUFFIXES
    ]
    if not rendered:
        return True, "no rendered animations present"

    # Every module here, not just render_*.py: the render scripts share helpers (_common.py),
    # and editing one of those changes the animations just as much as editing a script does.
    sources = list(RENDER_DIR.glob("*.py"))
    sources += list((ROOT / "src" / "thermolab").rglob("*.py"))
    if not sources:
        return False, "no render scripts"

    newest = max(sources, key=lambda p: p.stat().st_mtime)
    oldest = min(rendered, key=lambda p: p.stat().st_mtime)
    if newest.stat().st_mtime > oldest.stat().st_mtime:
        return True, f"{newest.relative_to(ROOT)} is newer than {oldest.relative_to(ROOT)}"
    return False, f"{len(rendered)} animation file(s) up to date"


def build_animations(mode: str) -> Stage:
    """mode: 'auto' (render when stale), 'always', or 'never'."""
    heading("animations")
    if mode == "never":
        print("skipped (--no-media)")
        return Stage("animations", detail="skipped")

    if mode == "auto":
        stale, why = media_is_stale()
        if not stale:
            print(f"skipped — {why} (force with --media)")
            return Stage("animations", detail="up to date")
        print(f"rendering — {why}")

    scripts = sorted(RENDER_DIR.glob("render_*.py"))
    if not scripts:
        print("no render scripts found")
        return Stage("animations", detail="none")

    problems: list[str] = []
    for script in scripts:
        print(f"--- {script.relative_to(ROOT)}")
        result = subprocess.run([sys.executable, str(script)], cwd=ROOT)
        if result.returncode != 0:
            problems.append(f"{script.relative_to(ROOT)} exited {result.returncode}")

    return Stage(
        "animations",
        ok=not problems,
        detail=f"{len(scripts)} script(s)",
        problems=problems,
    )


def clean_build_outputs(lang: str) -> list[str]:
    """Drop the previous build's output, staged assets and cached page ASTs for one language.

    `site/content` has to go with the rest. It caches each page's processed AST, including
    which media file every figure resolved to, and MyST will reuse a stale entry: when the
    pages were switched from .gif to .mp4 sources, a spared cache made the Hebrew copy ship
    the superseded .gif while English — whose cache happened to be invalidated — shipped the
    .mp4. Same source, two different animations, and nothing reported it.

    Deliberately spares `_build/templates`: that is the downloaded book theme, it is a cache
    worth keeping, and a running `myst start` holds an open handle on it — removing the whole
    `_build` fails with WinError 32 whenever a live preview is up. A lock on anything else is
    reported and tolerated rather than fatal, for the same reason: a dev server running
    alongside the build is a normal state, not a broken one.
    """
    problems: list[str] = []
    for relative in ("html", "site"):
        target = ROOT / "content" / lang / "_build" / relative
        if not target.exists():
            continue
        try:
            shutil.rmtree(target)
        except PermissionError as exc:
            problems.append(
                f"could not clean {target.relative_to(ROOT)} ({exc.strerror}) — "
                "stop `myst start` if the site ships superseded images"
            )
    return problems


def build_language(lang: str, clean: bool, base_path: str) -> tuple[Path, list[str]]:
    problems = clean_build_outputs(lang) if clean else []

    env = os.environ.copy()
    env["BASE_URL"] = f"{base_path}/{lang}"
    print(f"--- {lang} (BASE_URL={env['BASE_URL']})")
    subprocess.run(
        [myst_executable(), "build", "--html"],
        cwd=ROOT / "content" / lang,
        env=env,
        check=True,
    )
    out = ROOT / "content" / lang / "_build" / "html"
    if not out.exists():
        sys.exit(f"expected build output missing: {out}")
    return out, problems


def build_languages(clean: bool, base_path: str) -> tuple[dict[str, Path], Stage]:
    """Build each language project, from scratch unless asked otherwise.

    The clean matters more than it looks — see `clean_build_outputs` for what a reused
    `_build` costs: superseded copies of every re-rendered animation piling up in the
    published site, and figures resolving to the media file they pointed at some builds ago.
    """
    heading("myst")
    if not clean:
        print("reusing existing _build (--no-clean) — may ship superseded image copies")

    builds: dict[str, Path] = {}
    problems: list[str] = []
    for lang in LANGS:
        builds[lang], lang_problems = build_language(lang, clean, base_path)
        problems.extend(lang_problems)

    for problem in problems:
        print(f"warning: {problem}")
    # Warn rather than fail: the pages themselves built, and the usual cause is a live preview
    # holding a lock, which is a normal thing to be doing. It is loud in the summary because
    # the result can genuinely be wrong — a spared cache can pin a figure to superseded media.
    return builds, Stage("myst", detail=f"{len(builds)} language(s)", problems=problems)


def lab_link_targets() -> set[str]:
    """Every root-absolute /lite/... path the content links to, without its query string.

    Read from the sources rather than the built HTML so this works before MyST has run and
    stays independent of how the theme happens to render a link.
    """
    targets = set()
    for lang in LANGS:
        for page in (ROOT / "content" / lang).rglob("*.md"):
            for match in LAB_LINK.findall(page.read_text(encoding="utf-8")):
                targets.add(urlsplit(match).path.lstrip("/"))
    return targets


def write_lab_redirects() -> list[Path]:
    """Bridge each language's /lite/ address to the one shared bundle at the site root.

    MyST prefixes a root-absolute link target with BASE_URL, so `/lite/lab/index.html` written
    in a page is emitted as `<base>/<lang>/lite/lab/index.html`. There is no bundle there — it
    lives once at `<base>/lite/` — so every laboratory link 404s. The two ways out are copying
    the 70 MB bundle into each language tree or answering at the address MyST generates; this
    is the second.

    The redirect is deliberately *relative*: `../../../lite/lab/index.html` resolves to
    `<base>/lite/lab/index.html` whatever `<base>` is, so the same output works when served
    from a domain root and from a GitHub Pages project prefix. It is JavaScript rather than a
    meta refresh because `?path=<notebook>` — the whole point of the link — has to survive.
    """
    written = []
    for target in sorted(lab_link_targets()):
        for lang in LANGS:
            shim = SITE / lang / target
            up = "../" * len(Path(f"{lang}/{target}").parent.parts)
            destination = f"{up}{target}"
            shim.parent.mkdir(parents=True, exist_ok=True)
            shim.write_text(
                "<!DOCTYPE html>\n"
                '<html lang="en">\n'
                "<head>\n"
                '<meta charset="utf-8">\n'
                "<title>ThermoLab laboratory</title>\n"
                f'<script>location.replace("{destination}" + location.search + location.hash);'
                "</script>\n"
                "</head>\n"
                "<body>\n"
                f'<p><a href="{destination}">Open the laboratory</a></p>\n'
                "</body>\n"
                "</html>\n",
                encoding="utf-8",
            )
            written.append(shim)
    return written


def assemble(builds: dict[str, Path]) -> Stage:
    heading("assemble")
    if SITE.exists():
        shutil.rmtree(SITE)
    SITE.mkdir()

    counts = []
    for lang in LANGS:
        shutil.copytree(builds[lang], SITE / lang)
        pages = len(list((SITE / lang).rglob("*.html")))
        print(f"{lang}: {pages} pages")
        counts.append(f"{lang}={pages}")

    (SITE / "index.html").write_text(ROOT_REDIRECT, encoding="utf-8")
    print(f"wrote {(SITE / 'index.html').relative_to(ROOT)}")
    for shim in write_lab_redirects():
        print(f"wrote {shim.relative_to(ROOT)} (laboratory redirect)")
    return Stage("assemble", detail=", ".join(counts))


def expected_lite_notebooks() -> list[Path]:
    """Where each authored notebook must land inside the bundle.

    `LiteBuildConfig.contents: ["notebooks"]` copies the *contents* of notebooks/ to the
    root of the file tree, so notebooks/he/labs/04-pressure.ipynb is served from
    _site/lite/files/he/labs/04-pressure.ipynb — the path the module pages link to.
    """
    expected = []
    for lang in LANGS:
        source = ROOT / "notebooks" / lang
        if not source.exists():
            continue
        for notebook in sorted(source.rglob("*.ipynb")):
            if ".ipynb_checkpoints" in notebook.parts:
                continue
            expected.append(SITE / "lite" / "files" / notebook.relative_to(ROOT / "notebooks"))
    return expected


def verify_lab_links() -> list[str]:
    """Check that every laboratory link in the content actually lands on something.

    Both halves of a lab link can be wrong independently: the notebook named by `?path=` may
    not be in the bundle, and the address MyST generates for the link may have no redirect
    answering it. The second is how all five links silently 404ed — the pages looked right and
    nothing checked where they pointed.
    """
    problems = []
    for lang in LANGS:
        for page in sorted((ROOT / "content" / lang).rglob("*.md")):
            for match in LAB_LINK.findall(page.read_text(encoding="utf-8")):
                split = urlsplit(match)
                target = split.path.lstrip("/")
                where = page.relative_to(ROOT)

                if not (SITE / target).exists():
                    problems.append(f"{where}: nothing at /{target} in the bundle")
                if not (SITE / lang / target).exists():
                    problems.append(f"{where}: no redirect at /{lang}/{target} — link will 404")

                notebook = split.query.removeprefix("path=")
                if split.query and not (SITE / "lite" / "files" / notebook).exists():
                    problems.append(f"{where}: linked notebook not in bundle: {notebook}")
    return problems


def verify_wheel() -> list[str]:
    """Check that the course package reached the bundle's package index.

    Without it `piplite.install("thermolab")` has nothing to install and every notebook fails
    on its first import — in the browser only, so no test on this machine would notice.
    """
    index = SITE / "lite" / "pypi" / "all.json"
    if not index.exists():
        return [f"missing {index.relative_to(ROOT)} — no wheel was indexed for piplite"]

    packages = json.loads(index.read_text(encoding="utf-8"))
    if PACKAGE not in packages:
        return [f"{PACKAGE} is not in {index.relative_to(ROOT)} — notebooks cannot import it"]
    return []


def verify_lite() -> list[str]:
    problems = []
    app = SITE / "lite" / "lab" / "index.html"
    if not app.exists():
        problems.append(f"missing {app.relative_to(ROOT)} — the ?path= lab links will 404")

    missing = [p for p in expected_lite_notebooks() if not p.exists()]
    for path in missing:
        problems.append(f"notebook not in bundle: {path.relative_to(ROOT)}")

    problems += verify_lab_links()
    problems += verify_wheel()
    if not problems:
        print(f"verified lab app + {len(expected_lite_notebooks())} notebook(s), links and wheel")
    return problems


def build_wheel() -> Stage:
    """Build the thermolab wheel that JupyterLite serves to Pyodide.

    The browser kernel has no access to this repository, so the package has to travel with the
    bundle: `jupyter_lite_config.json` points PipliteAddon at `dist/`, which copies the wheel
    into `_site/lite/pypi/` and indexes it. The directory is emptied first — the index picks up
    every wheel it finds, so one left over from an earlier version would be published too.
    """
    heading("wheel")
    if WHEEL_DIR.exists():
        shutil.rmtree(WHEEL_DIR)

    result = subprocess.run(
        [uv_executable(), "build", "--wheel", "--out-dir", str(WHEEL_DIR)],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print((result.stderr or result.stdout).strip()[-2000:])
        return Stage("wheel", ok=False, problems=[f"uv build exited {result.returncode}"])

    wheels = sorted(WHEEL_DIR.glob("*.whl"))
    for wheel in wheels:
        print(f"built {wheel.relative_to(ROOT)}")
    if not wheels:
        return Stage("wheel", ok=False, problems=["uv build produced no wheel"])
    return Stage("wheel", detail=wheels[0].name)


def build_jupyterlite() -> Stage:
    """Bundle the notebooks into a browser-runnable JupyterLite app at _site/lite/.

    This is what lets a reader open a laboratory without installing anything: Pyodide runs
    the same `thermolab` code in the browser.

    The doit database is cleared first. It caches task state against outputs that we have
    just deleted along with `_site/`, and a stale entry makes the build report success while
    copying nothing — which is exactly how the bundle went missing without anyone noticing.
    A failure here is fatal: the module pages link into /lite/, so shipping without it means
    shipping dead links.
    """
    heading("jupyterlite")
    LITE_DOIT_DB.unlink(missing_ok=True)

    result = subprocess.run(
        [sys.executable, "-m", "jupyter", "lite", "build"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print((result.stderr or result.stdout).strip()[-2000:])
        failure = f"jupyter lite build exited {result.returncode}"
        return Stage("jupyterlite", ok=False, problems=[failure])

    problems = verify_lite()
    if problems:
        print((result.stderr or result.stdout).strip()[-2000:])
    return Stage("jupyterlite", ok=not problems, detail=str(SITE / "lite"), problems=problems)


def serve(port: int, base_path: str) -> None:
    if base_path:
        # Serving the tree at the root contradicts the prefix the pages were built with, so
        # every internal link would point one level too deep. Say so rather than let the
        # reader conclude the build is broken.
        print(
            f"\nnot serving: this build targets {base_path}/, so it must be served from that "
            f"path. Copy _site to <root>{base_path} and serve <root>."
        )
        return

    print(f"\nserving {SITE} at http://localhost:{port}/  (Ctrl-C to stop)")
    print(f"  English   http://localhost:{port}/en/")
    print(f"  Hebrew    http://localhost:{port}/he/")
    print(f"  Labs      http://localhost:{port}/lite/lab/index.html?path=en/labs/04-pressure.ipynb")
    try:
        subprocess.run(
            [sys.executable, "-m", "http.server", str(port), "--directory", str(SITE)], cwd=ROOT
        )
    except KeyboardInterrupt:
        pass


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--no-lite", action="store_true", help="skip the JupyterLite bundle")
    parser.add_argument(
        "--no-clean",
        action="store_true",
        help="reuse content/<lang>/_build instead of rebuilding it (faster, may ship stale assets)",
    )
    media = parser.add_mutually_exclusive_group()
    media.add_argument("--media", action="store_true", help="always re-render animations (slow)")
    media.add_argument("--no-media", action="store_true", help="never render animations")
    parser.add_argument(
        "--serve",
        nargs="?",
        type=int,
        const=8000,
        metavar="PORT",
        help="serve _site/ after a successful build (default port 8000)",
    )
    parser.add_argument(
        "--base-path",
        default=os.environ.get("SITE_BASE_PATH", ""),
        metavar="PREFIX",
        help="path the site is served under, e.g. /thermolab for a GitHub Pages project site "
        "(default: $SITE_BASE_PATH, else the domain root)",
    )
    args = parser.parse_args(argv)

    ensure_stdout_can_print_unicode()

    base_path = normalise_base_path(args.base_path)
    media_mode = "always" if args.media else "never" if args.no_media else "auto"
    stages = [build_stylesheets(), build_quizzes(), build_animations(media_mode)]

    builds, myst_stage = build_languages(clean=not args.no_clean, base_path=base_path)
    stages.append(myst_stage)
    stages.append(assemble(builds))

    if args.no_lite:
        heading("jupyterlite")
        print("skipped (--no-lite) — /lite/ links on module pages will 404")
        stages.append(Stage("jupyterlite", detail="skipped"))
    else:
        stages.append(build_wheel())
        stages.append(build_jupyterlite())

    heading("summary")
    width = max(len(stage.name) for stage in stages)
    for stage in stages:
        status = ("WARN" if stage.problems else "OK  ") if stage.ok else "FAIL"
        suffix = f"  ({stage.detail})" if stage.detail else ""
        print(f"{stage.name.ljust(width)}  {status}{suffix}")
        for problem in stage.problems:
            print(f"{' ' * width}    - {problem}")

    if not all(stage.ok for stage in stages):
        print("\nbuild FAILED")
        return 1

    served_at = f"{base_path}/" if base_path else "/"
    print(f"\nbuild OK -> {SITE}  (to be served at {served_at})")
    if args.serve is not None:
        serve(args.serve, base_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
