"""Generate each language's stylesheet from the shared/RTL sources.

mystmd's `site.options.style` takes ONE local CSS file per project, so we compose them:
    en -> theme/_shared.css
    he -> theme/_shared.css + theme/_rtl.css
Output lands in content/<lang>/thermolab.css. The generated files are committed so that
`myst start` (single-language live preview) works without running a build step first.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
THEME = ROOT / "theme"
SOURCES = {"en": ["_shared.css"], "he": ["_shared.css", "_rtl.css"]}
BANNER = "/* GENERATED by scripts/build_css.py from theme/{sources} — do not edit. */\n\n"


def generate() -> list[Path]:
    written = []
    for lang, names in SOURCES.items():
        parts = [BANNER.format(sources=", ".join(names))]
        parts += [(THEME / name).read_text(encoding="utf-8") for name in names]
        target = ROOT / "content" / lang / "thermolab.css"
        target.write_text("\n".join(parts), encoding="utf-8")
        written.append(target)
    return written


if __name__ == "__main__":
    for path in generate():
        print(f"[build_css] wrote {path.relative_to(ROOT)}")
