"""Generate site quiz pages and jupyterquiz JSON from `assessment/quizzes/*.yml` banks.

Quiz banks are the single source of truth (`assessment/quizzes/<module>.<lang>.yml`);
this script is the only thing that writes the two renderings:

- `content/<lang>/_generated/quiz-<module>.md` — a MyST disclosure block per question.
  Site pages cannot run JavaScript (see `.claude/CLAUDE.md` "Site build"), so the
  self-check is a `:::{dropdown}` the reader opens, not a graded widget.
- `notebooks/<lang>/_quiz/<module>.json` — jupyterquiz JSON for auto-graded questions
  in the notebooks. `prediction`/`short-answer` questions have no automatic grader,
  so they are skipped here (they still appear on the site rendering, with their
  `discussion` as the disclosure content).

Idempotent: output depends only on the YAML input, so re-running with unchanged
banks produces byte-identical files.

Run standalone (`python scripts/render_quizzes.py`) or import `check()` / `generate()`.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _findings import Finding, report  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
QUIZ_DIR = ROOT / "assessment" / "quizzes"

GENERATED_BANNER = "<!-- GENERATED by scripts/render_quizzes.py from {source} -- do not edit. -->"

# UI strings live here, keyed by language, so a new language only needs an entry here.
UI_STRINGS = {
    "en": {"check_answer": "Check your answer", "correct_answer": "Correct answer"},
    "he": {"check_answer": "בדקו את התשובה", "correct_answer": "התשובה הנכונה"},
}

# jupyterquiz's own type names, for the question types it can auto-grade.
AUTO_GRADED_TYPES = {"multiple-choice": "multiple_choice", "numeric": "numeric"}


def render_site_markdown(module: str, lang: str, bank: dict) -> str:
    strings = UI_STRINGS[lang]
    lines = [GENERATED_BANNER.format(source=f"assessment/quizzes/{module}.{lang}.yml"), ""]

    for i, question in enumerate(bank.get("questions") or [], start=1):
        qtype = question.get("type")
        lines.append(f"{i}. {(question.get('prompt') or '').strip()}")
        lines.append("")

        if qtype == "multiple-choice":
            choices = question.get("choices") or []
            # Options are lettered so the feedback can refer to them without repeating the
            # whole option text, which made the disclosure block unreadable. The letters are
            # Latin in both languages: they are labels, and a reader scanning back up the
            # list matches shapes, not words.
            labels = [chr(ord("A") + index) for index in range(len(choices))]
            for label, choice in zip(labels, choices, strict=True):
                lines.append(f"   {label}. {choice.get('text', '')}")
            lines.append("")
            lines.append(f"   :::{{dropdown}} {strings['check_answer']}")
            correct_index = next(
                (index for index, c in enumerate(choices) if c.get("correct")), None
            )
            if correct_index is not None:
                lines.append(
                    f"   **{strings['correct_answer']}: {labels[correct_index]}** — "
                    f"{choices[correct_index].get('text', '')}"
                )
                lines.append("")
            for label, choice in zip(labels, choices, strict=True):
                lines.append(f"   - **{label}.** {choice.get('feedback', '')}")
            lines.append("   :::")
        elif qtype == "numeric":
            lines.append(f"   :::{{dropdown}} {strings['check_answer']}")
            lines.append(
                f"   **{strings['correct_answer']}:** {question.get('answer')} "
                f"(± {question.get('tolerance')})"
            )
            feedback = question.get("feedback")
            if feedback:
                lines.append("")
                lines.append(f"   {feedback}")
            lines.append("   :::")
        else:  # prediction / short-answer: no auto-gradable answer, just discussion
            lines.append(f"   :::{{dropdown}} {strings['check_answer']}")
            lines.append(f"   {question.get('discussion', '')}")
            lines.append("   :::")

        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def render_notebook_json(bank: dict) -> list[dict]:
    questions = []
    for question in bank.get("questions") or []:
        qtype = question.get("type")
        jq_type = AUTO_GRADED_TYPES.get(qtype)
        if jq_type is None:
            continue
        entry: dict = {"question": (question.get("prompt") or "").strip(), "type": jq_type}
        if qtype == "multiple-choice":
            entry["answers"] = [
                {
                    "answer": choice.get("text", ""),
                    "correct": bool(choice.get("correct", False)),
                    "feedback": choice.get("feedback", ""),
                }
                for choice in question.get("choices") or []
            ]
        elif qtype == "numeric":
            answer = question.get("answer")
            tolerance = question.get("tolerance")
            entry["answers"] = [
                {
                    "range": [answer - tolerance, answer + tolerance],
                    "correct": True,
                    "feedback": question.get("feedback", ""),
                }
            ]
        questions.append(entry)
    return questions


def render_module(root: Path, module: str, lang: str, bank: dict) -> list[Path]:
    written: list[Path] = []

    site_dir = root / "content" / lang / "_generated"
    site_dir.mkdir(parents=True, exist_ok=True)
    site_path = site_dir / f"quiz-{module}.md"
    body = render_site_markdown(module, lang, bank)

    # Generated Hebrew pages carry the same `en_source_hash` stamp as hand-written ones, so
    # check_parity.py can treat every page under content/he uniformly. The hash is of the
    # generated English page, which is why the English language is rendered first.
    if lang != "en":
        english = root / "content" / "en" / "_generated" / f"quiz-{module}.md"
        if english.exists():
            digest = hashlib.sha256(english.read_bytes().replace(b"\r\n", b"\n")).hexdigest()
            body = f"% en_source_hash: {digest}\n\n{body}"

    site_path.write_text(body, encoding="utf-8", newline="\n")
    written.append(site_path)

    notebook_dir = root / "notebooks" / lang / "_quiz"
    notebook_dir.mkdir(parents=True, exist_ok=True)
    notebook_path = notebook_dir / f"{module}.json"
    payload = json.dumps(render_notebook_json(bank), indent=2, ensure_ascii=False) + "\n"
    notebook_path.write_text(payload, encoding="utf-8", newline="\n")
    written.append(notebook_path)

    return written


def generate(root: Path = ROOT) -> tuple[list[Path], list[Finding]]:
    written: list[Path] = []
    findings: list[Finding] = []
    quiz_dir = root / "assessment" / "quizzes"
    if not quiz_dir.exists():
        return written, findings

    for path in sorted(quiz_dir.glob("*.*.yml")):
        try:
            module, lang, _ext = path.name.rsplit(".", 2)
        except ValueError:
            findings.append(
                Finding(path, None, "error", f"unexpected quiz bank filename: {path.name}")
            )
            continue
        if lang not in UI_STRINGS:
            findings.append(Finding(path, None, "error", f"no UI strings for language '{lang}'"))
            continue
        try:
            bank = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        except yaml.YAMLError as exc:
            findings.append(Finding(path, None, "error", f"invalid YAML: {exc}"))
            continue
        if not isinstance(bank.get("questions"), list):
            findings.append(Finding(path, None, "error", "quiz bank has no questions: list"))
            continue
        written.extend(render_module(root, module, lang, bank))

    return written, findings


def check(root: Path = ROOT) -> list[Finding]:
    _written, findings = generate(root)
    return findings


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", action="store_true", help="machine-readable output")
    args = parser.parse_args(argv)
    written, findings = generate()
    if not args.json:
        for path in written:
            print(f"wrote {path.relative_to(ROOT)}")
    return report(findings, args.json)


if __name__ == "__main__":
    raise SystemExit(main())
